version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: cmd/app/Dockerfile
    ports:
      - 8080:8080
    environment:
      - HTTP_SERVER_ADDRESS=${HTTP_SERVER_ADDRESS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - JobCronTime=${JobCronTime}
    depends_on:
      - postgres
  cron:
    build:
      context: .
      dockerfile: cmd/cron/Dockerfile
    environment:
      - HTTP_SERVER_ADDRESS=${HTTP_SERVER_ADDRESS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - JobCronTime=${JobCronTime}
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=currency